### ISSUE TITLE
org.bimserver.shared.exceptions.UserException

### ISSUE THREAD

**Issue by arlem03** [opensourceBIM/IfcPlugins#17]
Hello 
I am using BIMserver version 1.5.147.

When I try to load the ifcengine-latest.zip or any other version using "Available Plugin Bundle" function on BIMviews, I first get "INSTALLPLUGINBUNDLEFROMFILE_BUSY" then I get the following error:

      "org.bimserver.shared.exceptions.UserException."

When I try to load the ifcopenshellplugin-0-5.60.jar, I get the following error: "Java.net.UnknownHostException:s3.amazonaws.com: Name or service not known." Any other plugins I get "org.bimserver.shared.exceptions.UserException."

I do not know why I am getting this error. I searched the net for a solution but couldn't find any. I am not sure what I am missing. I am not that familiar with BIMserver. I would appreciate your help greatly.

**Comment by rubendel** [comment]
s3.amazonaws.com could not be resolved, must be your internet connection. Yesterday there were some pretty big routing issues on the internet so I am guessing it would have been that, can you try again?

**Comment by arlem03** [comment]
Thank you. I tried again and it gave me the same error. I didn't know that installing a plugin from a file located in my server needed to connect to the internet. I assume the corporate firewall is blocking this specific connection. Could this be the reason, and is the "org.bimserver.shared.exceptions.UserException" related to the same issue?

**Comment by arlem03** [comment]
I have noticed the following error in the bimserver.log after I attempted to install a plugin from my files. I do not have anything using this database beside BIMserver itself. My user access is root. Have you ran into something like this and were able to resolve it? 

7458 [localhost-startStop-1] ERROR org.bimserver.BimServer - 
org.bimserver.database.berkeley.DatabaseInitException: Environment locked exception. Another process is using the same database, or the current user has no write access (database location: "/opt/bimserver/apache-tomcat-8.5.41/webapps/bimserver/WEB-INF/database")
	at org.bimserver.database.berkeley.BerkeleyKeyValueStore.<init>(BerkeleyKeyValueStore.java:117)
	at org.bimserver.BimServer.start(BimServer.java:661)
	at org.bimserver.web.WarServerInitializer.contextInitialized(WarServerInitializer.java:117)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:744)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:980)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1851)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
7488 [localhost-startStop-1] INFO  o.b.s.websockets.jsr356.Jsr356Impl - WebSocket context initialized

**Comment by rubendel** [comment]
Pretty sure another process is using the database, or... well as the error says no write access.

Running BIMserver (or almost anything) as root is not recommended.

**Comment by arlem03** [comment]
Ok, I'll check this out and let you know.

**Comment by arlem03** [comment]
I haven't had any luck with loading IfcPlugin. I have tried several versions to no avail. I now get this error:

2019-07-13 08:47:18,053 ERROR [org.bimserver.PluginInterface.installPluginBundleFromFile] o.b.d.a.InstallPluginBundleFromBytes [InstallPluginBundleFromBytes.java:68] 
java.lang.NullPointerException: null
	at org.bimserver.database.actions.InstallPluginBundleFromBytes.execute(InstallPluginBundleFromBytes.java:57)
	at org.bimserver.database.actions.InstallPluginBundleFromBytes.execute(InstallPluginBundleFromBytes.java:35)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:735)
	at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:727)
	at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundleFromFile(PluginServiceImpl.java:1456)
	at org.bimserver.generated.PluginInterfaceReflectorqxfvZkBXFAXE_1.callMethod(PluginInterfaceReflectorqxfvZkBXFAXE_1.java)
	at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:223)
	at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:166)
	at org.bimserver.JsonHandler.execute(JsonHandler.java:77)
	at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:67)
	at org.bimserver.servlets.RootServlet.service(RootServlet.java:141)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by arlem03** [comment]
Any alternative to BIMServer. I can't make this work for the life of me.
