### ISSUE TITLE
java.lang.OutOfMemoryError while loading large files

### ISSUE THREAD

**Issue by rebeccasc** [opensourceBIM/IfcPlugins#19]
Hi, first of all thanks for the great plugins!
While using the deserializer I had some troubles with loading large files. What I get is an `java.lang.OutOfMemoryError` that looks either like this (`Java heap space`)

```
[Test worker] INFO org.bimserver.emf.PackageMetaData - Initializing IFC2X3TC1 with ifc2x3tc1
[Test worker] INFO nl.tue.buildingsmart.emf.SchemaLoader - IFC-Schema successfully loaded from IFC2X3_TC1.exp
Jun 01, 2021 10:50:11 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNUNG: TestEngine with ID 'junit-jupiter' failed to execute tests
java.lang.OutOfMemoryError: Java heap space
	at org.eclipse.emf.ecore.impl.EStructuralFeatureImpl$InternalSettingDelegateMany.createDynamicSetting(EStructuralFeatureImpl.java:1671)
	at org.eclipse.emf.ecore.impl.EStructuralFeatureImpl$InternalSettingDelegateMany.dynamicGet(EStructuralFeatureImpl.java:1723)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1027)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1011)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:1003)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eGet(BasicEObjectImpl.java:998)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.readList(IfcStepDeserializer.java:385)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processRecord(IfcStepDeserializer.java:341)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processLine(IfcStepDeserializer.java:229)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:152)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:132)
```

or like this (`GC overhead limit exceeded`)

```
[Test worker] INFO org.bimserver.emf.PackageMetaData - Initializing IFC2X3TC1 with ifc2x3tc1
[Test worker] INFO nl.tue.buildingsmart.emf.SchemaLoader - IFC-Schema successfully loaded from IFC2X3_TC1.exp
Jun 01, 2021 10:52:05 AM org.junit.platform.launcher.core.DefaultLauncher handleThrowable
WARNUNG: TestEngine with ID 'junit-jupiter' failed to execute tests
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.eclipse.emf.ecore.impl.MinimalEObjectImpl.eSettings(MinimalEObjectImpl.java:736)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eDynamicUnset(BasicEObjectImpl.java:1214)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eUnset(BasicEObjectImpl.java:1188)
	at org.eclipse.emf.ecore.impl.BasicEObjectImpl.eUnset(BasicEObjectImpl.java:1158)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processRecord(IfcStepDeserializer.java:362)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.processLine(IfcStepDeserializer.java:229)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:152)
	at org.bimserver.ifc.step.deserializer.IfcStepDeserializer.read(IfcStepDeserializer.java:132)
```

Is there an easy way to fix this? 

Btw: I know `IfcStepDeserializer` is deprecated. Is there any example of how to use the `Ifc4StepStreamingDeserializer`? 

Thanks!

**Comment by hlg** [comment]
The only way to fix this would be to assign more memory to your JVM. The non-streaming deserializers read the whole IFC into memory before storage. The streaming deserializers on the other hand write the IFC entities to the database on the fly - with a much smaller memory footprint. Keep in mind that the deserializers are plugins for BIMserver to store IFC to the dababase. They are meant to be used with BIMserver and in the case of streaming deserializers their standalone use would not make sense. With inversion of control BIMserver provides the interface, plugins implement it, such that BIMserver can then use those implementation. You are right that documentation is missing for streaming deserializer plugins, but that would only cover plugin development/implementation, not its usage.

If you aim to recreate an environment similar to BIMserver that works with the streaming deserializer interfaces, you could read the source code to see how BIMserver uses them. But I would not recommend doing this and would rather appreciate you using the BIMserver and help improve it towards your use case. In the medium to long term it might be worth figuring out how to streamline BIMserver usage as a backend for one-off data processing use cases such as yours.
